13/04/21 (05:08:17) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 927, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
17/05/21 (06:45:20) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 935, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
05/06/21 (21:24:38) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 935, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
08/07/21 (05:46:52) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 937, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
03/08/21 (19:36:42) | ERROR: Exception when sending signal 9 to pid 38197
03/08/21 (19:36:42) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5459, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
03/08/21 (19:36:46) | ERROR: Exception when sending signal 9 to pid 38197
03/08/21 (19:36:46) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5459, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
03/08/21 (19:36:56) | ERROR: Exception when sending signal 15 to pid 38197
03/08/21 (19:36:56) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5459, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
10/08/21 (21:38:18) | ERROR: Data collection thread failed with exception: Precision not allowed in integer format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2939, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3971, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2751, in _draw_fg
    (f'{proc.details["threads"]:^{iw}.{iw2}}' if expand > 0 else "") + (f'{proc.details["nice"]:^{iw}.{iw2}}' if expand > 1 else "") +
ValueError: Precision not allowed in integer format specifier
10/08/21 (21:38:18) | WARNING: Exiting with errorcode (1). Runtime 0:01:46 

